### ISSUE TITLE
Move UIWebView to WKWebView?

### ISSUE THREAD

**Issue by rafaelmaeuer** [CocoaBob/GBA4iOS#7]
Hey alltogether,

I saw recent activity on this project and want to commit that I was working hard the past weeks to move from UIWebView to WKWebView dependency as Apple now rejects Apps due to deprecation.
Besides moving to AFNetworking v4 I needed to upgrade the underlying dependencies RSTWebViewController and NJKWebViewProgress to use WKWebView too.

You can use my forks of the updated dependencies if you want:
https://github.com/rafaelmaeuer/RSTWebViewController-Legacy
https://github.com/rafaelmaeuer/NJKWebViewProgress
I didn't pushed them on cocoapods, so you need to set github as source in podfile.

If you are interested I could also put my private GBA4iOS-fork online, where I also did some improvements regarding deprecated API-usage, skin loading and the WKWebView-Upgrade.

**Comment by CocoaBob** [comment]
Hi Rafael,

Yes, UIWebView is deprecated. Since the author of this project @rileytestut has abandoned it and is working on the new emulator [Delta](https://github.com/rileytestut/Delta), please feel free to contribute, and don't hesitate to share what you've done to the public 😉

Personally I've switched to [Delta](https://github.com/rileytestut/Delta) and some physical Nintendo consoles. There are many refurbished GB/GBC/GBA consoles with IPS screen mod on eBay. IPS screen is awesome, looks perfect! And [EZ-Flash Omega/Junior](http://www.ezflash.cn) are also perfect for these retro consoles. I just find much fun with them during the lockdown period 😂

**Comment by rafaelmaeuer** [comment]
I put the code of my fork online, so if anyone else needs the update to WKWebView feel free to use: https://github.com/rafaelmaeuer/GBA4iOS
